// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SISPR.Models.DataBase;

namespace SISPR.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20210728121716_1")]
    partial class _1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.8");

            modelBuilder.Entity("SISPR.Models.DataBase.UTP.Forma_obuchen", b =>
                {
                    b.Property<int>("forma_obuchen_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .HasColumnType("longtext");

                    b.HasKey("forma_obuchen_id");

                    b.ToTable("Forma_obuchen");
                });

            modelBuilder.Entity("SISPR.Models.DataBase.UTP.Type_training_load", b =>
                {
                    b.Property<int>("type_training_load_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .HasColumnType("longtext");

                    b.Property<float>("number_control_forms")
                        .HasColumnType("float");

                    b.Property<float>("number_groups")
                        .HasColumnType("float");

                    b.Property<float>("number_hours")
                        .HasColumnType("float");

                    b.Property<float>("number_listeners")
                        .HasColumnType("float");

                    b.Property<float>("number_subgroups")
                        .HasColumnType("float");

                    b.Property<int>("type")
                        .HasColumnType("int");

                    b.Property<float>("volume_hours")
                        .HasColumnType("float");

                    b.HasKey("type_training_load_id");

                    b.ToTable("Type_training_load");
                });

            modelBuilder.Entity("SISPR.Models.DataBase.UTP.UTP", b =>
                {
                    b.Property<int>("utp_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("forma_obuchen_id")
                        .HasColumnType("int");

                    b.Property<float>("hour")
                        .HasColumnType("float");

                    b.Property<int>("kol_groups")
                        .HasColumnType("int");

                    b.Property<int>("kol_slushatel_v_group")
                        .HasColumnType("int");

                    b.Property<int>("kol_subgroups")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .HasColumnType("longtext");

                    b.Property<int>("rejim_zanyati")
                        .HasColumnType("int");

                    b.HasKey("utp_id");

                    b.ToTable("UTPs");
                });

            modelBuilder.Entity("SISPR.Models.DataBase.UTP.UTP_type_training_load", b =>
                {
                    b.Property<int>("utp_type_training_load_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("type_training_load_id")
                        .HasColumnType("int");

                    b.Property<int>("utp_id")
                        .HasColumnType("int");

                    b.HasKey("utp_type_training_load_id");

                    b.ToTable("UTP_type_training_load");
                });
#pragma warning restore 612, 618
        }
    }
}
